DB authentication and role based access configured
mate-academy/jv-spring-security-part-2 pull request #259
Opened 2022-09-07 12:23 UTC by SpaceUrgent

Role entity, dao, service created;
DB authentication configured;
Role based access configured.

2022-09-07 15:34 UTC, zachar-chorny requested changes

2022-09-07 15:34 UTC, zachar-chorny commented on src/main/java/mate/academy/spring/model/User.java
empty line

2022-09-07 15:34 UTC, zachar-chorny commented on src/main/java/mate/academy/spring/security/CustomUserDetailsService.java
> +import static org.springframework.security.core.userdetails.User.withUsername;
```suggestion
import static org.springframework.security.core.userdetails.User;
```
You should not import statics in this way. Then it is not clear which class the method belongs to

2022-09-07 15:34 UTC, zachar-chorny commented on src/main/java/mate/academy/spring/security/CustomUserDetailsService.java
> +        UserBuilder userBuilder = withUsername(username);
```suggestion
        UserBuilder userBuilder = User.withUsername(username);
```

2022-09-07 17:53 UTC, SpaceUrgent commented
![image](https://user-images.githubusercontent.com/104736240/188945386-039c3fe4-4d09-4176-b43d-6d2c1d766988.png)

The issue i can't do import like this is because we will have here two Users class so the Error in compiler will appear. So i can only move the package reference to method in order to create the visibality of which class method was called.

2022-09-08 16:18 UTC, MaliukDaria approved these changes

2022-09-08 16:18 UTC, MaliukDaria commented on src/main/java/mate/academy/spring/config/DataInitializer.java
> +    @Autowired
use @Autowired everywhere or nowhere

2022-09-08 16:18 UTC, MaliukDaria commented on src/main/java/mate/academy/spring/config/DataInitializer.java
> +
redundant empty line

2022-09-08 16:18 UTC, MaliukDaria commented on src/main/java/mate/academy/spring/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/register").anonymous()
why not permitAll()?

2022-09-08 16:18 UTC, MaliukDaria commented on src/main/java/mate/academy/spring/security/CustomUserDetailsService.java
> +            throw new UsernameNotFoundException("User not found");
```suggestion
            throw new UsernameNotFoundException("There is no user with email " + username);
```

2025-03-09 18:07 UTC, closed without merging